#!/bin/bash
#This is script of function that use to check palindrome words
#This assignmnet is done by Danayit Girma (GSR/2925/15) and Jale Lijalem (GSR/2053/15)
echo "Welcome to palindrome checker UI"
palindrome ()
{
        echo "Please enter the string"
        read string
        length=$(echo -n "$string" | wc -m)
        i=$((length-1))
        while [[ $i -ge 0 ]]
        do
                reverse=$reverse${string:$i:1}
                i=$((i-1))
        done
}
echo "Do u want to insert string?, if not, please insert q"
read answer
while [[ $answer == "yes" ]]
do
        echo "Enter any word except q to continue"
        read answer2
        if [[ $answer2 == "q" ]]
        then
                echo "Thank you for using the service"
                exit
        else
                palindrome
                if [[ $string == $reverse ]]
                then
                        echo "The word $string is palindrome word"
                else
                        echo "The word $string is not palindrome word"
                fi
                unset reverse
        fi
done
echo "Thank you for visiting the service"
